import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{seedItems,recommendations}from'./data';
import{supabase,hasSupabase}from'./lib/supabase';
import'./styles.css';

const LS_ITEMS='morgana-hub-items-v2';
const LS_CHECK='morgana-hub-checklist-v2';
const LS_GIFTS='morgana-hub-gifts-v2';
const LS_EVENTS='morgana-hub-events-v2';
const LS_THEME='morgana-hub-theme-v1';
const LS_CUSTOM_RECS='morgana-hub-custom-recommendations-v1';
const DUE_DATE='2026-11-17';
const fmt=n=>new Intl.NumberFormat('pt-BR').format(Number(n)||0);
const priRank={Alta:0,Média:1,Condicional:2,Baixa:3};
const slug=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const missingRecs=recommendations.filter(r=>r.status==='FALTA').sort((a,b)=>(priRank[a.priority]??9)-(priRank[b.priority]??9));
const seedChecklist=missingRecs.map(r=>({id:`check-${slug(r.item)}`,name:r.item,category:r.category,quantity:Math.max(1,r.min-r.current),priority:r.priority,note:r.note,size:'',age:'',unit:r.category.includes('Roupas')?'peça':'unid.'}));
const seedGifts=missingRecs.filter(r=>r.priority!=='Condicional').map(r=>({id:`gift-${slug(r.item)}`,name:r.item,category:r.category,quantity:Math.max(1,r.min-r.current),status:'available',buyer:'',note:r.note,purchased_at:null,received_at:null}));

function safeLoad(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function saveLocal(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function dateOnly(d){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d)}
function isoLocalDate(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return`${y}-${m}-${day}`}
const sameNeed=(a,b)=>slug(a?.name||a?.item||'')===slug(b?.name||b?.item||'');

function App(){
 const[tab,setTab]=useState('inicio');
 const[items,setItems]=useState(seedItems);
 const[checklist,setChecklist]=useState(seedChecklist);
 const[gifts,setGifts]=useState(seedGifts);
 const[events,setEvents]=useState([]);
 const[customRecs,setCustomRecs]=useState([]);
 const[q,setQ]=useState('');
 const[cat,setCat]=useState('Todas');
 const[sizeFilter,setSizeFilter]=useState('Todos');
 const[sort,setSort]=useState({key:'name',dir:'asc'});
 const[recSort,setRecSort]=useState({key:'item',dir:'asc'});
 const[showItem,setShowItem]=useState(false);
 const[showEvent,setShowEvent]=useState(false);
 const[showWish,setShowWish]=useState(false);
 const[showRecommendation,setShowRecommendation]=useState(false);
 const[giftChoice,setGiftChoice]=useState(null);
 const[sync,setSync]=useState(hasSupabase?'conectando':'local');
 const[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
 const[theme,setTheme]=useState(()=>{try{return localStorage.getItem(LS_THEME)||'light'}catch{return'light'}});

 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem(LS_THEME,theme)}catch{}},[theme]);
 useEffect(()=>{let channel;(async()=>{
   const keyOf=x=>`${x.category}|${x.name}|${x.size||''}|${x.age||''}`;
   if(!hasSupabase){
     const savedItems=safeLoad(LS_ITEMS,seedItems);const existing=new Set(savedItems.map(keyOf));
     setItems([...seedItems.filter(x=>x.category==='Fraldas'&&!existing.has(keyOf(x))),...savedItems]);
     setChecklist(safeLoad(LS_CHECK,seedChecklist));setGifts(safeLoad(LS_GIFTS,seedGifts));setEvents(safeLoad(LS_EVENTS,[]));setCustomRecs(safeLoad(LS_CUSTOM_RECS,[]));return;
   }
   setSync('conectando');
   const[ir,cr,gr,er,rr]=await Promise.all([
     supabase.from('items').select('*').order('created_at'),
     supabase.from('checklist').select('*').order('created_at'),
     supabase.from('gifts').select('*').order('created_at'),
     supabase.from('calendar_events').select('*').order('event_date').order('event_time'),
     supabase.from('custom_recommendations').select('*').order('created_at')
   ]);
   if(!ir.error){if(ir.data?.length){const existing=new Set(ir.data.map(keyOf)),missing=seedItems.filter(x=>x.category==='Fraldas'&&!existing.has(keyOf(x)));if(missing.length)await supabase.from('items').insert(missing);setItems([...ir.data,...missing])}else{await supabase.from('items').insert(seedItems);setItems(seedItems)}}
   if(!cr.error){if(cr.data?.length)setChecklist(cr.data);else{await supabase.from('checklist').insert(seedChecklist);setChecklist(seedChecklist)}}
   if(!gr.error){if(gr.data?.length)setGifts(gr.data);else{await supabase.from('gifts').insert(seedGifts);setGifts(seedGifts)}}
   if(!er.error)setEvents(er.data||[]);
   if(!rr.error)setCustomRecs(rr.data||[]);
   setSync([ir.error,cr.error,gr.error,er.error,rr.error].some(Boolean)?'parcial':'online');
   channel=supabase.channel('morgana-hub-live-v33')
    .on('postgres_changes',{event:'*',schema:'public',table:'items'},async()=>{const{data}=await supabase.from('items').select('*').order('created_at');if(data)setItems(data)})
    .on('postgres_changes',{event:'*',schema:'public',table:'gifts'},async()=>{const{data}=await supabase.from('gifts').select('*').order('created_at');if(data)setGifts(data)})
    .on('postgres_changes',{event:'*',schema:'public',table:'checklist'},async()=>{const{data}=await supabase.from('checklist').select('*').order('created_at');if(data)setChecklist(data)})
    .on('postgres_changes',{event:'*',schema:'public',table:'calendar_events'},async()=>{const{data}=await supabase.from('calendar_events').select('*').order('event_date').order('event_time');if(data)setEvents(data)})
    .on('postgres_changes',{event:'*',schema:'public',table:'custom_recommendations'},async()=>{const{data}=await supabase.from('custom_recommendations').select('*').order('created_at');if(data)setCustomRecs(data)})
    .subscribe();
 })();return()=>{if(channel)supabase.removeChannel(channel)}},[]);
 useEffect(()=>{if(!hasSupabase){saveLocal(LS_ITEMS,items);saveLocal(LS_CHECK,checklist);saveLocal(LS_GIFTS,gifts);saveLocal(LS_EVENTS,events);saveLocal(LS_CUSTOM_RECS,customRecs)}},[items,checklist,gifts,events,customRecs]);

 async function persistItems(next){setItems(next);if(!hasSupabase)return;setSync('salvando');const del=await supabase.from('items').delete().neq('id',0);if(del.error){setSync('erro');return}if(next.length){const ins=await supabase.from('items').insert(next.map(({id,created_at,...x})=>x));if(ins.error){setSync('erro');return}}setSync('online')}
 async function persistChecklist(next){setChecklist(next);if(!hasSupabase)return;setSync('salvando');const del=await supabase.from('checklist').delete().neq('id','__never__');if(del.error){setSync('erro');return}if(next.length){const ins=await supabase.from('checklist').insert(next.map(({created_at,...x})=>x));if(ins.error){setSync('erro');return}}setSync('online')}
 async function persistGifts(next){setGifts(next);if(!hasSupabase)return;setSync('salvando');const del=await supabase.from('gifts').delete().neq('id','__never__');if(del.error){setSync('erro');return}if(next.length){const ins=await supabase.from('gifts').insert(next.map(({created_at,...x})=>x));if(ins.error){setSync('erro');return}}setSync('online')}
 async function persistCustomRecs(next){setCustomRecs(next);if(!hasSupabase)return;setSync('salvando');const del=await supabase.from('custom_recommendations').delete().neq('id','__never__');if(del.error){setSync('erro');return}if(next.length){const ins=await supabase.from('custom_recommendations').insert(next.map(({created_at,...x})=>x));if(ins.error){setSync('erro');return}}setSync('online')}

 async function addToInventory(entry,qty=1){
   const name=entry.name,category=entry.category||'Outros',size=entry.size||'',age=entry.age||'';
   const idx=items.findIndex(x=>slug(x.name)===slug(name)&&x.category===category&&(x.size||'')===size&&(x.age||'')===age);
   let next;if(idx>=0)next=items.map((x,i)=>i===idx?{...x,quantity:Number(x.quantity||0)+Number(qty||1)}:x);else next=[...items,{name,category,quantity:Number(qty)||1,size,age,brand:entry.brand||'',unit:entry.unit||'unid.'}];
   await persistItems(next);return next;
 }
 function delta(i,d){persistItems(items.map((x,k)=>k===i?{...x,quantity:Math.max(0,Number(x.quantity)+d)}:x))}
 function addItem(e){e.preventDefault();const f=new FormData(e.currentTarget),x={name:f.get('name'),category:f.get('category'),quantity:Number(f.get('quantity')||1),size:f.get('size')||'',age:f.get('age')||'',brand:f.get('brand')||'',unit:f.get('unit')||'unid.'};persistItems([...items,x]);setShowItem(false)}
 function checklistFromGift(g){return{id:`check-${slug(g.name)}`,name:g.name,category:g.category,quantity:g.quantity||1,priority:g.priority||'Média',note:g.note||'',product_url:g.product_url||'',size:g.size||'',age:g.age||'',unit:g.unit||'unid.'}}
 async function removeChecklistFor(entry){await persistChecklist(checklist.filter(x=>!sameNeed(x,entry)))}
 async function hideGiftAfterFamilyPurchase(entry){const match=gifts.find(g=>sameNeed(g,entry)&&g.status==='available');if(!match)return;await persistGifts(gifts.map(g=>g.id===match.id?{...g,status:'received',buyer:'Comprado pela família',received_at:new Date().toISOString()}:g))}
 async function buyChecklist(c){await addToInventory(c,c.quantity);await removeChecklistFor(c);await hideGiftAfterFamilyPurchase(c)}
 async function chooseGift(e){e.preventDefault();const f=new FormData(e.currentTarget),buyer=(f.get('buyer')||'Anônimo').trim();const updated={...giftChoice,status:'purchased',buyer,purchased_at:new Date().toISOString()};const existing=gifts.find(g=>sameNeed(g,updated)&&g.status!=='received');const next=existing?gifts.map(g=>g.id===existing.id?{...updated,id:existing.id}:g):[...gifts,updated];await persistGifts(next);await removeChecklistFor(updated);setGiftChoice(null)}
 async function confirmGift(g){await addToInventory(g,g.quantity);await removeChecklistFor(g);await persistGifts(gifts.map(x=>x.id===g.id?{...g,status:'received',received_at:new Date().toISOString()}:x))}
 async function releaseGift(g){const updated={...g,status:'available',buyer:'',purchased_at:null,received_at:null};await persistGifts(gifts.map(x=>x.id===g.id?updated:x));if(!checklist.some(c=>sameNeed(c,g)))await persistChecklist([...checklist,checklistFromGift(g)])}
 async function addWish(e){
   e.preventDefault();const f=new FormData(e.currentTarget),name=(f.get('name')||'').trim();if(!name)return;
   const category=f.get('category')||'Outros',quantity=Math.max(1,Number(f.get('quantity')||1)),priority=f.get('priority')||'Média',note=f.get('note')||'',product_url=(f.get('product_url')||'').trim(),base=slug(name);
   const c={id:`check-${base}`,name,category,quantity,priority,note,product_url,size:'',age:'',unit:'unid.'};
   const g={id:`gift-${base}`,name,category,quantity,status:'available',buyer:'',note,product_url,purchased_at:null,received_at:null};
   const existingC=checklist.find(x=>sameNeed(x,c));const existingG=gifts.find(x=>sameNeed(x,g)&&x.status!=='received');
   const nextC=existingC?checklist.map(x=>sameNeed(x,c)?{...x,...c,id:x.id}:x):[...checklist,c];
   const nextG=existingG?gifts.map(x=>x.id===existingG.id?{...x,category,quantity,note,product_url}:x):[...gifts,g];
   await Promise.all([persistChecklist(nextC),persistGifts(nextG)]);setShowWish(false);setTab('checklist');
 }
 async function addCustomRecommendation(e){e.preventDefault();const f=new FormData(e.currentTarget),name=(f.get('name')||'').trim();if(!name)return;const category=f.get('category')||'Outros',target=Math.max(1,Number(f.get('target')||1)),note=(f.get('note')||'').trim(),id=`custom-${Date.now()}`;await persistCustomRecs([...customRecs,{id,name,category,target,note}]);setShowRecommendation(false)}
 async function deleteCustomRecommendation(r){await persistCustomRecs(customRecs.filter(x=>x.id!==r.id))}

 async function addEvent(e){e.preventDefault();const f=new FormData(e.currentTarget),ev={id:`evt-${Date.now()}`,title:f.get('title'),event_date:f.get('date'),event_time:f.get('time')||null,event_type:f.get('type')||'Tarefa',notes:f.get('notes')||'',done:false};if(hasSupabase){setSync('salvando');const{error}=await supabase.from('calendar_events').insert(ev);if(error){console.error(error);setSync('erro');alert(`Não foi possível salvar no modo online: ${error.message}`);return}setSync('online')}setEvents([...events,ev].sort((a,b)=>`${a.event_date}${a.event_time||''}`.localeCompare(`${b.event_date}${b.event_time||''}`)));setShowEvent(false);setMonth(new Date(`${ev.event_date}T12:00:00`))}
 async function toggleEvent(ev){const updated={...ev,done:!ev.done};setEvents(events.map(x=>x.id===ev.id?updated:x));if(hasSupabase)await supabase.from('calendar_events').update({done:updated.done}).eq('id',ev.id)}
 async function deleteEvent(ev){setEvents(events.filter(x=>x.id!==ev.id));if(hasSupabase)await supabase.from('calendar_events').delete().eq('id',ev.id)}

 const totals=useMemo(()=>({fraldas:items.filter(x=>x.category==='Fraldas').reduce((a,b)=>a+Number(b.quantity||0),0),roupas:items.filter(x=>x.category==='Roupas').reduce((a,b)=>a+Number(b.quantity||0),0)}),[items]);
 const cats=['Todas',...Array.from(new Set(items.map(x=>x.category))).sort()];
 const sizes=['Todos',...Array.from(new Set(items.map(x=>(x.size||'').trim()).filter(Boolean))).sort((a,b)=>a.localeCompare(b,'pt-BR',{numeric:true}))];
 const filtered=useMemo(()=>items.filter(x=>(cat==='Todas'||x.category===cat)&&(sizeFilter==='Todos'||(x.size||'')===sizeFilter)&&(`${x.name} ${x.size} ${x.age} ${x.category}`.toLowerCase().includes(q.toLowerCase()))),[items,cat,sizeFilter,q]);
 const sortedItems=useMemo(()=>[...filtered].sort((a,b)=>{const av=sort.key==='quantity'?Number(a.quantity||0):String(a[sort.key]||'').toLocaleLowerCase('pt-BR'),bv=sort.key==='quantity'?Number(b.quantity||0):String(b[sort.key]||'').toLocaleLowerCase('pt-BR');const cmp=typeof av==='number'?av-bv:av.localeCompare(bv,'pt-BR',{numeric:true});return sort.dir==='asc'?cmp:-cmp}),[filtered,sort]);
 function changeSort(key){setSort(s=>s.key===key?{key,dir:s.dir==='asc'?'desc':'asc'}:{key,dir:'asc'})}
 function changeRecSort(key){setRecSort(s=>s.key===key?{key,dir:s.dir==='asc'?'desc':'asc'}:{key,dir:'asc'})}
 const diapers=items.filter(x=>x.category==='Fraldas');const maxD=Math.max(...diapers.map(x=>Number(x.quantity)||0),1);
 const clothingStock=useMemo(()=>{const map=new Map();items.filter(x=>x.category==='Roupas').forEach(x=>{const key=`${x.name}|${x.size||'—'}|${x.age||''}`;const old=map.get(key)||{name:x.name,size:x.size||'—',age:x.age||'',quantity:0};old.quantity+=Number(x.quantity||0);map.set(key,old)});return[...map.values()].sort((a,b)=>b.quantity-a.quantity||a.name.localeCompare(b.name,'pt-BR'))},[items]);
 const maxC=Math.max(...clothingStock.map(x=>x.quantity),1);
 const pendingGifts=gifts.filter(g=>g.status==='purchased');
 const availableGifts=useMemo(()=>checklist.map(c=>{const existing=gifts.find(g=>sameNeed(g,c)&&g.status==='available');return existing?{...existing,name:c.name,category:c.category,quantity:c.quantity,note:c.note,product_url:c.product_url||existing.product_url||'',size:c.size||existing.size||'',age:c.age||existing.age||'',priority:c.priority||existing.priority||'Média'}:{id:`gift-${slug(c.name)}`,name:c.name,category:c.category,quantity:c.quantity,status:'available',buyer:'',note:c.note||'',product_url:c.product_url||'',size:c.size||'',age:c.age||'',priority:c.priority||'Média',purchased_at:null,received_at:null}}),[checklist,gifts]);
 const liveRecommendations=useMemo(()=>recommendations.map(r=>{let current=r.current;if(r.item.startsWith('Fraldas ')){const sz=r.item.split(' ').pop(),d=items.find(i=>i.category==='Fraldas'&&i.size===sz);current=Number(d?.quantity||0)}else{const extra=items.filter(i=>slug(i.name)===slug(r.item)).reduce((a,b)=>a+Number(b.quantity||0),0);current=r.current+extra}const status=current<r.min?'FALTA':current>r.max?'SOBRA':'OK';return{...r,current,status,custom:false}}),[items]);
 const customLiveRecommendations=useMemo(()=>customRecs.map(r=>{const matches=items.filter(i=>slug(i.name)===slug(r.name)&&(!r.category||r.category==='Todos'||i.category===r.category));const current=matches.reduce((a,b)=>a+Number(b.quantity||0),0),target=Number(r.target||0),status=current<target?'FALTA':current>target?'SOBRA':'OK';return{item:r.name,category:r.category,current,min:target,max:target,note:r.note||'Meta adicionada pela família.',status,custom:true,id:r.id,target}}),[customRecs,items]);
 const allRecommendations=useMemo(()=>[...liveRecommendations,...customLiveRecommendations],[liveRecommendations,customLiveRecommendations]);
 const sortedRecommendations=useMemo(()=>[...allRecommendations].sort((a,b)=>{const statusRank={FALTA:0,OK:1,SOBRA:2};const value=r=>recSort.key==='current'?Number(r.current||0):recSort.key==='reference'?Number(r.custom?r.target:r.min):recSort.key==='status'?(statusRank[r.status]??9):String(r.item||'').toLocaleLowerCase('pt-BR');const av=value(a),bv=value(b),cmp=typeof av==='number'?av-bv:String(av).localeCompare(String(bv),'pt-BR',{numeric:true});return recSort.dir==='asc'?cmp:-cmp}),[allRecommendations,recSort]);
 const upcomingEvents=events.filter(e=>!e.done&&e.event_date>=isoLocalDate(new Date())).sort((a,b)=>`${a.event_date}${a.event_time||''}`.localeCompare(`${b.event_date}${b.event_time||''}`));
 const preg=useMemo(()=>{const due=new Date(`${DUE_DATE}T12:00:00`),start=new Date(due);start.setDate(start.getDate()-280);const now=new Date(),total=due-start,elapsed=Math.max(0,Math.min(total,now-start)),pct=Math.round(elapsed/total*100),days=Math.floor(elapsed/86400000);return{pct,weeks:Math.floor(days/7),rem:days%7,remaining:Math.max(0,Math.ceil((due-now)/86400000))}},[]);
 const title=tab==='inicio'?'Olá, Morgana ♡':tab==='inventario'?'Inventário completo':tab==='recomendacoes'?'Recomendações':tab==='checklist'?'Checklist pré-nascimento':tab==='presentes'?'Presentes para a Morgana':'Calendário da família';
 const headerAction=tab==='inventario'?<button className="primary" onClick={()=>setShowItem(true)}>＋ Adicionar item</button>:tab==='recomendacoes'?<button className="primary" onClick={()=>setShowRecommendation(true)}>＋ Adicionar recomendação</button>:tab==='checklist'?<button className="primary" onClick={()=>setShowWish(true)}>＋ Adicionar item</button>:tab==='presentes'?null:tab==='calendario'?<button className="primary" onClick={()=>setShowEvent(true)}>＋ Novo compromisso</button>:null;

 return <div className="app"><aside><div className="brand"><span>✦</span><div><b>Morgana Hub</b><small>Enxoval & preparação</small></div></div>{[['inicio','⌂','Início'],['inventario','▦','Inventário'],['recomendacoes','✓','Recomendações'],['checklist','☑','Checklist'],['presentes','♡','Presente'],['calendario','◫','Calendário']].map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])} key={x[0]}><span>{x[1]}</span>{x[2]}</button>)}<div className="sync">● {sync==='online'?'Sincronizado online':sync==='salvando'?'Salvando…':sync==='parcial'?'Sincronização parcial':sync==='erro'?'Erro de sincronização':sync==='conectando'?'Conectando…':'Modo local'}<small>{hasSupabase?'Supabase conectado · dados compartilhados':'Modo local · configure o Supabase para sincronizar entre dispositivos'}</small></div></aside><main><header><div><h1>{title}</h1><p>{tab==='inicio'?'Tudo o que vocês já têm, o que falta e os próximos compromissos.':tab==='presentes'?'Escolha um item disponível para presentear a Morgana.':tab==='calendario'?'Consultas, exames, tarefas e compromissos em um só lugar.':tab==='recomendacoes'?'Faixas práticas de referência comparadas ao estoque atual.':'Dados do enxoval da Morgana.'}</p></div><div className="headerActions"><button className="themeToggle" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?'☾ Escuro':'☀ Claro'}</button>{headerAction}</div></header>

 {tab==='inicio'&&<><section className="hero"><div><span className="eyebrow">GESTAÇÃO</span><h2>Preparando tudo para a chegada da Morgana</h2><p>DPP: <b>17/11/2026</b> · {preg.weeks} semanas e {preg.rem} dias · {preg.remaining} dias até a data prevista.</p></div><div className="progressRing" style={{'--pct':`${preg.pct*3.6}deg`}}><b>{preg.pct}%</b><span>da gestação</span></div></section>
 <section className="homeCalendar"><div className="homeCalendarHead"><div><span className="eyebrow">CALENDÁRIO</span><h2>Próximos compromissos</h2><p>Consultas, exames e tarefas importantes para organizar a rotina da família.</p></div><div className="calendarActions"><button onClick={()=>setShowEvent(true)}>＋ Novo</button><button onClick={()=>setTab('calendario')}>Abrir calendário →</button></div></div>{upcomingEvents.length?<div className="homeAgendaGrid">{upcomingEvents.slice(0,3).map(e=><article className="homeEvent" key={e.id}><div className="homeDate"><b>{new Date(`${e.event_date}T12:00:00`).getDate()}</b><span>{new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(new Date(`${e.event_date}T12:00:00`)).replace('.','')}</span></div><div><small>{e.event_type}</small><h3>{e.title}</h3><p>{e.event_time?`${e.event_time} · `:''}{e.notes||'Sem observações adicionais'}</p></div><button onClick={()=>toggleEvent(e)}>✓</button></article>)}</div>:<div className="homeCalendarEmpty"><span>◫</span><div><b>Nenhum compromisso futuro cadastrado.</b><small>Adicione consultas, exames ou tarefas para visualizar tudo aqui.</small></div><button onClick={()=>setShowEvent(true)}>Adicionar compromisso</button></div>}</section>
 {pendingGifts.length>0&&<section className="giftArrival"><div><span className="eyebrow">PRESENTES COMPRADOS</span><h3>{pendingGifts.length===1?'Tem um presente a caminho ♡':`${pendingGifts.length} presentes estão a caminho ♡`}</h3><p>Quando chegar, confirme aqui para atualizar o inventário e as recomendações automaticamente.</p></div><div className="giftArrivalItems">{pendingGifts.map(g=><article key={g.id}><span>♡</span><div><b>{g.name}</b><small>{g.buyer?`Presente de ${g.buyer}`:'Presente reservado'} · qtd. {g.quantity}</small></div><button className="confirm" onClick={()=>confirmGift(g)}>Recebemos ✓</button></article>)}</div></section>}
 <section className="cards compactCards"><KPI n={fmt(totals.fraldas)} l="fraldas" s="estoque total"/><KPI n={fmt(totals.roupas)} l="peças de roupa" s="catalogadas"/></section>
 <div className="stockPair"><section className="panel"><div className="panelTitle"><div><small>ESTOQUE</small><h3>Fraldas por tamanho</h3></div><button onClick={()=>setTab('inventario')}>ver inventário →</button></div><div className="bars">{diapers.map(d=><div className="barRow" key={d.name}><span>{d.size}</span><div><i style={{width:`${Number(d.quantity)/maxD*100}%`}}/></div><b>{fmt(d.quantity)}</b></div>)}</div></section><section className="panel clothesPanel"><div className="panelTitle"><div><small>ESTOQUE</small><h3>Roupas por peça e tamanho</h3></div><button onClick={()=>setTab('inventario')}>ver inventário →</button></div><div className="clothesBars">{clothingStock.slice(0,10).map(x=><div className="clothesRow" key={`${x.name}-${x.size}-${x.age}`}><div className="clothesLabel"><b>{x.name}</b><small>Tam. {x.size}{x.age?` · ${x.age}`:''}</small></div><div className="clothesBar"><i style={{width:`${x.quantity/maxC*100}%`}}/></div><strong>{fmt(x.quantity)}</strong></div>)}</div></section></div></>}

 {tab==='inventario'&&<section className="panel full"><div className="toolbar inventoryToolbar"><input placeholder="Buscar item, tamanho ou idade…" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Filtrar por categoria" value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Filtrar por tamanho" value={sizeFilter} onChange={e=>setSizeFilter(e.target.value)}>{sizes.map(sz=><option key={sz} value={sz}>{sz==='Todos'?'Todos os tamanhos':`Tamanho ${sz}`}</option>)}</select></div><div className="tableWrap"><table><thead><tr><SortTh label="Item" field="name" sort={sort} onSort={changeSort}/><SortTh label="Categoria" field="category" sort={sort} onSort={changeSort}/><SortTh label="Tamanho" field="size" sort={sort} onSort={changeSort}/><SortTh label="Faixa" field="age" sort={sort} onSort={changeSort}/><SortTh label="Qtd." field="quantity" sort={sort} onSort={changeSort}/></tr></thead><tbody>{sortedItems.map((x,i)=>{const idx=items.indexOf(x);return <tr key={`${x.name}-${x.size}-${x.age}-${i}`}><td><b>{x.name}</b><small>{x.brand}</small></td><td>{x.category}</td><td>{x.size||'—'}</td><td>{x.age||'—'}</td><td><div className="qty"><button onClick={()=>delta(idx,-1)}>−</button><b>{x.quantity}</b><button onClick={()=>delta(idx,1)}>＋</button></div></td></tr>})}</tbody></table></div></section>}

 {tab==='recomendacoes'&&<section className="panel full recommendationPanel"><div className="recommendationLegend"><div><span className="recDot sobra"/>Sobrando</div><div><span className="recDot ok"/>OK</div><div><span className="recDot falta"/>Falta</div><p>As referências originais vêm da análise do enxoval; metas personalizadas são valores definidos por vocês e comparados ao Inventário.</p></div><div className="recommendationList"><div className="recommendationHead"><RecSortButton label="Item" field="item" sort={recSort} onSort={changeRecSort}/><RecSortButton label="Temos" field="current" sort={recSort} onSort={changeRecSort}/><RecSortButton label="Referência / meta" field="reference" sort={recSort} onSort={changeRecSort}/><RecSortButton label="Status" field="status" sort={recSort} onSort={changeRecSort}/></div>{sortedRecommendations.map(r=><article className={`recommendationRow ${r.status.toLowerCase()}`} key={r.custom?r.id:r.item}><div><b>{r.item}{r.custom&&<span className="customTag">Meta personalizada</span>}</b><small>{r.note}</small></div><strong>{fmt(r.current)}</strong><span>{r.custom?`Meta: ${fmt(r.target)}`:`${fmt(r.min)}–${fmt(r.max)}`}</span><em><i className={`recDot ${r.status.toLowerCase()}`}/>{r.status==='SOBRA'?'Sobrando':r.status==='FALTA'?'Falta':'OK'}{r.custom&&<button className="recDelete" onClick={()=>deleteCustomRecommendation(r)} title="Remover recomendação">×</button>}</em></article>)}</div></section>}

 {tab==='checklist'&&<section className="panel full"><div className="checkHeader"><div><small>ANTES DO NASCIMENTO</small><h3>Comprar / providenciar</h3></div><span>{checklist.length} pendências</span></div>{checklist.map(c=><div className="check purchase cleanCheck" key={c.id}><div><b>{c.name}</b><small>{c.note}{c.note?' · ':''}quantidade: {c.quantity}{c.product_url&&<> · <a className="productLink" href={c.product_url} target="_blank" rel="noreferrer">ver exemplo ↗</a></>}</small></div><em>{c.priority}</em><button onClick={()=>buyChecklist(c)}>Comprei ✓</button></div>)}{!checklist.length&&<Empty text="Tudo desta lista já foi providenciado. Os itens comprados foram adicionados ao inventário."/>}</section>}

 {tab==='presentes'&&<><section className="giftIntro"><div><span className="eyebrow">LISTA DE PRESENTES</span><h2>Quer presentear a Morgana?</h2><p>Esta lista mostra somente o que ainda está disponível. Ao marcar um presente como comprado, ele some daqui e do Checklist e fica aguardando confirmação na tela inicial.</p></div><span className="giftCount">{availableGifts.length}<small>disponíveis</small></span></section>{!hasSupabase&&<div className="notice">⚠️ Este Hub está em modo local. Para que convidados em outros celulares atualizem esta lista, conecte o Supabase na Vercel.</div>}<section className="giftGrid">{availableGifts.map(g=><article className="giftCard available" key={g.id}><div className="giftTop"><span>{g.category}</span><b>Disponível</b></div><h3>{g.name}</h3><p>{g.note}</p>{g.product_url&&<a className="giftProductLink" href={g.product_url} target="_blank" rel="noreferrer">Ver exemplo do item ↗</a>}<footer><span>Qtd. {g.quantity}</span><button className="primary" onClick={()=>setGiftChoice(g)}>Vou presentear ♡</button></footer></article>)}</section>{!availableGifts.length&&<Empty text="No momento não há itens disponíveis na lista de presentes."/>}</>}

 {tab==='calendario'&&<Calendar month={month} setMonth={setMonth} events={events} onToggle={toggleEvent} onDelete={deleteEvent} onAdd={()=>setShowEvent(true)}/>} 
 </main>

 {showItem&&<div className="modalBack" onMouseDown={()=>setShowItem(false)}><form className="modal" onSubmit={addItem} onMouseDown={e=>e.stopPropagation()}><div><h2>Adicionar item</h2><button type="button" onClick={()=>setShowItem(false)}>×</button></div><label>Nome<input required name="name"/></label><div className="two"><label>Categoria<select name="category">{cats.filter(x=>x!=='Todas').map(c=><option key={c}>{c}</option>)}<option>Outros</option></select></label><label>Quantidade<input name="quantity" type="number" min="0" defaultValue="1"/></label></div><div className="two"><label>Tamanho<input name="size"/></label><label>Idade / faixa<input name="age"/></label></div><div className="two"><label>Marca<input name="brand"/></label><label>Unidade<input name="unit" defaultValue="unid."/></label></div><button className="primary wide">Salvar item</button></form></div>}
 {showWish&&<div className="modalBack" onMouseDown={()=>setShowWish(false)}><form className="modal" onSubmit={addWish} onMouseDown={e=>e.stopPropagation()}><div><h2>Adicionar item desejado</h2><button type="button" onClick={()=>setShowWish(false)}>×</button></div><label>Item<input name="name" required placeholder="Ex.: Kit de mamadeiras"/></label><label>Categoria<select name="category"><option>Outros</option><option>Roupas</option><option>Higiene</option><option>Sono</option><option>Transporte</option><option>Saúde/rotina</option><option>Alimentação</option></select></label><div className="two"><label>Quantidade<input name="quantity" type="number" min="1" defaultValue="1"/></label><label>Prioridade<select name="priority" defaultValue="Média"><option>Alta</option><option>Média</option><option>Baixa</option></select></label></div><label>Link de exemplo <small>(opcional)</small><input name="product_url" type="url" placeholder="https://loja.com/produto"/></label><label>Observação<textarea name="note" placeholder="Opcional"/></label><p className="fine">O item, a quantidade e o link de exemplo serão sincronizados automaticamente entre Checklist e Presentes.</p><button className="primary wide">Adicionar item</button></form></div>}
 {showRecommendation&&<div className="modalBack" onMouseDown={()=>setShowRecommendation(false)}><form className="modal" onSubmit={addCustomRecommendation} onMouseDown={e=>e.stopPropagation()}><div><h2>Adicionar recomendação</h2><button type="button" onClick={()=>setShowRecommendation(false)}>×</button></div><label>Item<input name="name" list="inventory-item-options" required placeholder="Digite ou escolha um item do inventário"/></label><datalist id="inventory-item-options">{Array.from(new Set(items.map(x=>x.name))).sort((a,b)=>a.localeCompare(b,'pt-BR')).map(n=><option value={n} key={n}/>)}</datalist><label>Categoria<select name="category"><option>Todos</option>{Array.from(new Set(items.map(x=>x.category))).sort().map(c=><option key={c}>{c}</option>)}<option>Outros</option></select></label><label>Meta desejada<input name="target" type="number" min="1" defaultValue="1" required/></label><label>Observação<textarea name="note" placeholder="Ex.: vimos uma recomendação de ter 8 unidades"/></label><p className="fine">Se o item já existir no Inventário, a quantidade em “Temos” será puxada automaticamente e comparada à meta.</p><button className="primary wide">Adicionar recomendação</button></form></div>}
 {giftChoice&&<div className="modalBack" onMouseDown={()=>setGiftChoice(null)}><form className="modal giftModal" onSubmit={chooseGift} onMouseDown={e=>e.stopPropagation()}><div><h2>Presentear a Morgana ♡</h2><button type="button" onClick={()=>setGiftChoice(null)}>×</button></div><div className="selectedGift"><small>VOCÊ ESCOLHEU</small><b>{giftChoice.name}</b><span>Quantidade: {giftChoice.quantity}</span></div><label>Seu nome <small>(opcional)</small><input name="buyer" placeholder="Como a família vai identificar o presente"/></label><p className="fine">Ao confirmar, o item sai da lista pública e do Checklist para evitar compra duplicada.</p><button className="primary wide">Confirmar presente</button></form></div>}
 {showEvent&&<div className="modalBack" onMouseDown={()=>setShowEvent(false)}><form className="modal" onSubmit={addEvent} onMouseDown={e=>e.stopPropagation()}><div><h2>Novo compromisso</h2><button type="button" onClick={()=>setShowEvent(false)}>×</button></div><label>Título<input required name="title" placeholder="Ex.: Ultrassom, consulta, comprar item…"/></label><div className="two"><label>Data<input required type="date" name="date" defaultValue={isoLocalDate(new Date())}/></label><label>Horário<input type="time" name="time"/></label></div><label>Categoria<select name="type"><option>Consulta</option><option>Exame</option><option>Tarefa</option><option>Trabalho</option><option>Outro</option></select></label><label>Observação<textarea name="notes" rows="3" placeholder="Endereço, médico, lembrete para o trabalho…"/></label><button className="primary wide">Adicionar ao calendário</button></form></div>}
 </div>
}

function SortTh({label,field,sort,onSort}){return <th><button className="sortTh" onClick={()=>onSort(field)}>{label}<span>{sort.key===field?(sort.dir==='asc'?'▲':'▼'):'↕'}</span></button></th>}
function RecSortButton({label,field,sort,onSort}){return <button className="recSortButton" onClick={()=>onSort(field)}>{label}<span>{sort.key===field?(sort.dir==='asc'?'▲':'▼'):'↕'}</span></button>}
function EventRows({events,onToggle,onDelete,empty}){return <>{events.map(e=><div className={`agendaItem ${e.done?'done':''}`} key={e.id}><button className="agendaCheck" onClick={()=>onToggle(e)}>{e.done?'✓':'○'}</button><div><b>{e.title}</b><small>{dateOnly(new Date(`${e.event_date}T12:00:00`))}{e.event_time?` às ${e.event_time}`:''} · {e.event_type}</small>{e.notes&&<p>{e.notes}</p>}</div>{onDelete?<button className="trash" onClick={()=>onDelete(e)}>×</button>:<span/>}</div>)}{!events.length&&<Empty text={empty}/>}</>}
function Calendar({month,setMonth,events,onToggle,onDelete,onAdd}){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),offset=first.getDay(),cells=[];for(let i=0;i<offset;i++)cells.push(null);for(let d=1;d<=last.getDate();d++)cells.push(new Date(y,m,d));while(cells.length%7)cells.push(null);const monthEvents=events.filter(e=>{const d=new Date(`${e.event_date}T12:00:00`);return d.getFullYear()===y&&d.getMonth()===m}).sort((a,b)=>`${a.event_date}${a.event_time||''}`.localeCompare(`${b.event_date}${b.event_time||''}`));const upcoming=events.filter(e=>!e.done&&e.event_date>=isoLocalDate(new Date())).sort((a,b)=>`${a.event_date}${a.event_time||''}`.localeCompare(`${b.event_date}${b.event_time||''}`)).slice(0,8);const label=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(month);return <div className="calendarLayout"><section className="panel calendarPanel"><div className="calendarNav"><button onClick={()=>setMonth(new Date(y,m-1,1))}>‹</button><h2>{label}</h2><button onClick={()=>setMonth(new Date(y,m+1,1))}>›</button></div><div className="weekHead">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(x=><b key={x}>{x}</b>)}</div><div className="monthGrid">{cells.map((d,i)=>{if(!d)return <div className="day empty" key={`e${i}`}/>;const iso=isoLocalDate(d),dayEvents=events.filter(e=>e.event_date===iso),today=iso===isoLocalDate(new Date());return <div className={`day ${today?'today':''}`} key={iso}><span>{d.getDate()}</span>{dayEvents.slice(0,3).map(e=><i className={`evtDot ${e.done?'done':''}`} title={e.title} key={e.id}>{e.event_time||'•'} {e.title}</i>)}{dayEvents.length>3&&<small>+{dayEvents.length-3}</small>}</div>})}</div></section><div className="calendarSide"><section className="panel agendaSide"><div className="panelTitle"><div><small>AGENDA DO MÊS</small><h3>{monthEvents.length} compromissos</h3></div><button onClick={onAdd}>＋ adicionar</button></div><EventRows events={monthEvents} onToggle={onToggle} onDelete={onDelete} empty="Nenhum compromisso neste mês."/></section><section className="panel agendaSide"><div className="panelTitle"><div><small>PRÓXIMOS EVENTOS</small><h3>{upcoming.length} próximos</h3></div><button onClick={onAdd}>＋ adicionar</button></div><EventRows events={upcoming} onToggle={onToggle} onDelete={onDelete} empty="Nenhum evento futuro cadastrado."/></section></div></div>}
function Empty({text}){return <div className="emptyState">✦ <span>{text}</span></div>}
function KPI({n,l,s,warn}){return <article className={`kpi ${warn?'warn':''}`}><small>{s}</small><strong>{n}</strong><b>{l}</b></article>}
createRoot(document.getElementById('root')).render(<App/>);
